name: Build & Deploy

on:
  push:
    branches:
      - main
      
env:
  CI: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3  # Updated to v3
        with:
          node-version: 20  # You can adjust this to the required version for your project

      - name: Install dependencies
        run: npm ci  # Recommended to use npm ci for clean installs

      - name: Build project
        run: npm run build --loglevel verbose  # Added verbose logging for debugging

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3  # Confirming that this is already v3
        with:
          name: production-files
          path: ./build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3  # Updated to v3
        with:
          name: production-files
          path: ./build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Ensure you are using the correct secret
          publish_dir: ./build
