name: Build & Deploy

on:
  push:
    branches:
      - main

env:
  CI: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository (using v3)
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Setup Node.js (using v3)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Cache Node.js modules (optional, for faster builds)
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 4: Install dependencies
      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      # Step 5: Clean build directory (optional)
      - name: Clean build directory
        run: rm -rf ./build

      # Step 6: Build the project
      - name: Build project
        run: npm run build

      # Step 7: Upload production-ready build files (using v3 of upload-artifact)
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # Step 8: Download the artifact (using v3 of download-artifact)
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./build

      # Step 9: Deploy to GitHub Pages (using peaceiris/actions-gh-pages@v3)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
